<a href="https://colab.research.google.com/github/sakshimahadik463/Machine-Learning-with-python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##numpy package for multidimensional array

import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])     ##when we want create the array use np.array([])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(list_of_list)

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(4,100)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
       89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(91,1000000)

array([    91,     92,     93, ..., 999997, 999998, 999999])

In [ ]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(11,bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.zeros((2,5),int)       ##it will print 2 rows and 5 columns of zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
##create an array of zeros with 2 rows and 10 columns
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.linspace(0,1,5)  ##linspace---linearly spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.eye(3)    ##identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,2)

array([[0.49395827, 0.29049511],
       [0.13863448, 0.23644151],
       [0.27575459, 0.39640505]])

In [ ]:
np.random.randn(3,2)

array([[-0.86817342, -0.96970166],
       [-0.33305196,  0.35951882],
       [-0.37901085,  0.58731637]])

In [ ]:
np.random.randint(1,5)

1

In [ ]:
np.random.randint(1,5)   ##its giving random integers from 1 to 4

2

In [ ]:
np.random.randint(30,100,50)

array([95, 36, 88, 64, 67, 33, 38, 40, 90, 35, 63, 49, 41, 70, 56, 52, 55,
       85, 90, 58, 72, 61, 78, 81, 51, 41, 40, 59, 31, 88, 70, 57, 80, 63,
       39, 98, 58, 82, 88, 38, 65, 40, 51, 49, 79, 53, 67, 98, 63, 72])

In [ ]:
a=np.array(30)
a

array(30)

In [ ]:
b=np.arange(30)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
c=np.random.randint(0,100,20)
c

array([94, 43, 96, 40, 57, 31, 21, 96, 56, 15, 29, 10, 78, 82, 51, 41, 51,
       75, 64,  6])

In [ ]:
b.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
c.min()

6

In [ ]:
c.argmin()

19

In [ ]:
b.dtype

dtype('int64')

In [ ]:
x=np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
x=np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a.T

array(30)

In [ ]:
v=np.arange(10,21)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
v[3]

13

In [ ]:
v[3:7]

array([13, 14, 15, 16])

In [ ]:
v[1:4]=100
v

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [ ]:
v=np.arange(10,21)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
v[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_v=v[0:7]
subset_v

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_v[1:4]=1001
subset_v

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [ ]:
subset_v[:]=1001
subset_v

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [ ]:
##two dimensional array

import numpy as np

In [ ]:
a=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
a

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [ ]:
a[0:2,2]   ##0:2 is telling the range that is fromg 0th row and 1st row

array([ 1, 21])

In [ ]:
a[2,:]

array([56, 76, 24,  7])

In [ ]:
a[2]

array([56, 76, 24,  7])

In [ ]:
a[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [ ]:
b=np.arange(1,20)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
b+b ## b+b here the numbers from array b and array b are added and we will get a single array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [ ]:
np.exp(b)   ## exp stands for exponensial array b

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
np.sqrt(b)   ## sqrt stands for suareroot sample array or b

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
np.log(b)    ## log stands for log of array b

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [ ]:
np.max(b)   ## max stands for maximum of array b

19

In [ ]:
np.min(b)    ## min stands for minimum of array b

1

In [ ]:
np.argmax(b)    ## arg stands for argument i.e index of the max value

18

In [ ]:
np.argmin(b)   ## arg stands for argument i.e index of the min value

0

In [ ]:
np.square(b)  ## square to square the value

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [ ]:
np.std(b)    ## std = standard value

5.477225575051661

In [ ]:
np.var(b)

30.0

In [ ]:
np.mean(b)

10.0

In [ ]:
array=np.random.randn(3,4)
array

array([[ 1.92763509,  0.22781412, -1.47565534, -0.99318422],
       [-1.00288728, -2.47991866,  0.87321495, -1.10167697],
       [ 0.42405295, -1.96597748, -1.0300405 ,  1.44858465]])

In [ ]:
np.round(array,decimals=3) ## round is used to roundup the values upto 3 decimals

array([[ 1.928,  0.228, -1.476, -0.993],
       [-1.003, -2.48 ,  0.873, -1.102],
       [ 0.424, -1.966, -1.03 ,  1.449]])

In [ ]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')